version: 2
jobs:
  build:
    docker:
      - image: docker
          DOCKER_REPO: ycode/happyfl

    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Run docker build
          command: |
            TAG=v0.2.$CIRCLE_BUILD_NUM
            docker build -t $DOCKER_REPO:$TAG .
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push $DOCKER_REPO:$TAG

