version: 2
jobs:
  build:
    docker:
      - image: docker
        environment:
          TAG: 0.2.$CIRCLE_BUILD_NUM

    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Run docker build
          command:
            docker build -t ycode/happyfl:$TAG .
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push ycode/happyfl:$TAG

